const prompt=require('prompt-sync')()
var nota2=prompt("Dgite quantas notas de 2 reais você tem:")
var nota5=prompt("Dgite quantas notas de 5 reais você tem:")
var nota10=prompt("Dgite quantas notas de 10 reais você tem:")
var nota20=prompt("Dgite quantas notas de 20 reais você tem:")
var nota50=prompt("Dgite quantas notas de 50 reais você tem:")
var nota100=prompt("Dgite quantas notas de 100 reais você tem:")
var nota200=prompt("Dgite quantas notas de 200 reais você tem:")
resultado=(2*nota2+5*nota5+10*nota10+20*nota20+50*nota50+100*nota100+200*nota200)
console.log(parseInt(resultado))